services:

# Actions
    action.search.todos:
      class: TodoBundle\Application\Action\SearchTodo
      arguments: ["@service.fetchall.todos"]

    action.insert.category:
      class: TodoBundle\Application\Action\InsertCategory
      arguments: ['@service.insertnewcategory.category']

# Services
    service.fetchall.todos:
      class: TodoBundle\Domain\Todo\Service\FetchAllTodos
      arguments: ["@repository.todo"]

    service.insertnewcategory.category:
      class: TodoBundle\Domain\Category\Service\InsertNewCategory
      arguments: ['@repository.category']


# Repositories
    repository.todo:
      class: TodoBundle\Infrastructure\Repository\TodoRepository
      arguments: ['@doctrine']

    repository.category:
      class: TodoBundle\Infrastructure\Repository\CategoryRepository
      arguments: ['@doctrine']